/* Succinct db call using where
const productsRef = db.collection('products');
const query = productsRef.where('price', '<', 10); // where is a db qeury. here it's saying, get all products with a price that is less than 10

console.log({query});
query.get()
  .then(products => {
    products.forEach(doc => {
      data = doc.data()
      newElement(data.name + " at $" + data.price);
    })
  })
*/

/* Succinct addition to DOM
 function newElement(theText){
  var node = document.createElement("h1");                 // Create a <li> node
  node.id = "data-item";            //give it an ID
  node.innerText = theText;
  document.getElementById("theList").appendChild(node);              // Append the text to <li>
}
*/

/* Succinct Google Login method by Fireship
function googleLogin(){
    //Logins in user to google
    const provider = new firebase.auth.GoogleAuthProvider();
    firebase.auth().signInWithPopup(provider)

    .then(result => {
        const user = result.user;
        console.log(user);
        //document.write(`Hello ${user.displayName}`);
        document.getElementById("banner-login").innerText = `${user.displayName}`;
        //use the user object for something if you want
    })
    .catch(console.log);
} 
*/

/* simulate a click
function uploadClick(){
  document.getElementById("uploadInput").click();
}
*/

/* My attempt at uploading a file to Google Storage
function uploadFile(files){ //having problems getting the tutorial to work but this was lookin promising: https://firebase.googleblog.com/2016/07/5-tips-for-firebase-storage.html
  const file = files.item(0);   //takes first item in files list generated by input tag in html
  const storageRef = firebase.storage().ref(); //creates a reference for a path in storage bucket
  const horseRef = storageRef.child('horse.jpg'); //he says 'with this file, we can either 1) upload a file or 2) download an existing file URL
  const task = horseRef.put(file);

  task.then(snapshot => {
    horseRef.getDownloadURL().then(function(url){
    document.querySelector('#imgUpload').setAttribute('src', url);
    })
  })
}
*/

/* Some other 'Init map' function from google
function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 0, lng: 0},
      zoom: 3,
      styles: [{
        featureType: 'poi',
        stylers: [{ visibility: 'off' }]  // Turn off POI.
      },6
      {
        featureType: 'transit.station',
        stylers: [{ visibility: 'off' }]  // Turn off bus, train stations etc.
      }],
      disableDoubleClickZoom: true,
      streetViewControl: false,
    });
    console.log(map);
}*/